---
- name: Créer le dossier Alertmanager
  ansible.builtin.file:
    path: /opt/alertmanager
    state: directory
    mode: '0755'

- name: Récupérer la dernière version d'Alertmanager depuis GitHub
  ansible.builtin.shell: |
    curl -s https://api.github.com/repos/prometheus/alertmanager/releases/latest \
    | grep '"tag_name":' | cut -d '"' -f 4
  register: alertmanager_version
  changed_when: false

- name: Télécharger Alertmanager {{ alertmanager_version.stdout }}
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/{{ alertmanager_version.stdout }}/alertmanager-{{ alertmanager_version.stdout }}.linux-amd64.tar.gz"
    dest: /tmp/alertmanager.tar.gz

- name: Extraire Alertmanager
  ansible.builtin.unarchive:
    src: /tmp/alertmanager.tar.gz
    dest: /opt/alertmanager
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Copier le fichier de configuration alertmanager.yml
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: /opt/alertmanager/alertmanager.yml

- name: Lancer Alertmanager
  ansible.builtin.shell: |
    nohup /opt/alertmanager/alertmanager \
    --config.file=/opt/alertmanager/alertmanager.yml \
    --web.listen-address="0.0.0.0:9093" \
    > /var/log/alertmanager.log 2>&1 &
  args:
    creates: /tmp/alertmanager_running
