---
- name: Restauration du service GitLab
  hosts: vm_gitlab
  become: true

  tasks:
    - name: Restaurer la VM GitLab via Terraform
      command: terraform -chdir=terraform/gitlab apply -auto-approve
      register: terraform_result
      changed_when: "'Apply complete!' in terraform_result.stdout"

    - name: Attendre que la VM GitLab soit disponible
      wait_for_connection:
        timeout: 180

    - name: Réappliquer la configuration GitLab
      include_role:
        name: gitlab
