---
- name: Créer le dossier Prometheus
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory
    mode: '0755'

- name: Récupérer la dernière version de Prometheus sur GitHub
  ansible.builtin.shell: |
    curl -s https://api.github.com/repos/prometheus/prometheus/releases/latest \
    | grep '"tag_name":' | cut -d '"' -f 4
  register: prometheus_version
  changed_when: false

- name: Télécharger Prometheus {{ prometheus_version.stdout }}
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/{{ prometheus_version.stdout }}/prometheus-{{ prometheus_version.stdout }}.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz

- name: Extraire Prometheus
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/prometheus
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Copier le fichier de configuration prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /opt/prometheus/prometheus.yml

- name: Lancer Prometheus
  ansible.builtin.shell: |
    nohup /opt/prometheus/prometheus \
    --config.file=/opt/prometheus/prometheus.yml \
    --web.listen-address="0.0.0.0:9090" \
    > /var/log/prometheus.log 2>&1 &
  args:
    creates: /tmp/prometheus_running

- name: Déployer les règles d'alerte Prometheus
  ansible.builtin.template:
    src: alert_rules.yml.j2
    dest: /opt/prometheus/alert_rules.yml