---
- name: Créer le dossier Node Exporter
  ansible.builtin.file:
    path: /opt/node_exporter
    state: directory
    mode: '0755'

- name: Récupérer la dernière version de Node Exporter depuis GitHub
  ansible.builtin.shell: |
    curl -s https://api.github.com/repos/prometheus/node_exporter/releases/latest \
    | grep '"tag_name":' | cut -d '"' -f 4
  register: node_exporter_version
  changed_when: false

- name: Télécharger Node Exporter {{ node_exporter_version.stdout }}
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/{{ node_exporter_version.stdout }}/node_exporter-{{ node_exporter_version.stdout }}.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz

- name: Extraire Node Exporter
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt/node_exporter
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Lancer Node Exporter
  ansible.builtin.shell: |
    nohup /opt/node_exporter/node_exporter \
    --web.listen-address="0.0.0.0:9100" \
    > /var/log/node_exporter.log 2>&1 &
  args:
    creates: /tmp/node_exporter_running
